export const rootPath = "/"
export const blogPath = "/blog"
export const aboutPath = "/about"
export const cityPath = "/cities/:cityName"

export const welcomeHash = "/cities/:cityName#welcome"
export const eventsHash = "/cities/:cityName#events"
export const archivesHash = "/cities/:cityName#archives"
export const aboutHash = "/cities/:cityName#about"
export const contactHash = "/cities/:cityName#contact"
